title: Meta Front-End Developer

issuer: Meta and Coursera

issueDate: November 2, 2024

credentialUrl: https://www.coursera.org/account/accomplishments/professional-cert/KQSR7QEE6ZGJ

imageUrl: https://res.cloudinary.com/dof6n5t7s/image/upload/q_auto/f_auto/v1781972639/6897391a-f66a-4187-bf4f-b1d228bfbfec.png